blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/AJenbo/phpantom_lsp/tree/main/docs
    about: Check the docs before filing an issue. Your question might already be answered.